# CENSUS INCOME PROJECT

## Problem Statement:
In this project, initially you need to preprocess the data and then develop an understanding of different features of the data by performing exploratory analysis and creating visualizations.Further, after having sufficient knowledge about the attributes you will perform a predictive task of classification to predict whether an individual makes over 50K a year or less,by using different Machine Learning Algorithms 


### 1. Import packages

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [2]:
data = pd.read_csv("census-income.csv",na_values='?',skipinitialspace=True)
data

age         workclass  fnlwgt   education  education-num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country Unnamed: 14  
0              2174             0              40  United-States       <=50K  
1                 0             0              13  United-States       <=50K  
2                 0             0              40  United-States       <=50K  
3                 0             0              40  United-States       <=50K  
4                 0             0              40           Cuba       <=50K  
...             ...           ...             ...            ...         ...  
32556             0             0              38  United-States       <=50K  
32557             0             0              40  United-States        >50K  
32558             0             0              40  United-States       <=50K  
32559             0             0              20  United-States       <=50K  
32560         15024             0              40  United-States        >50K  

[32561 rows x 15 columns]

## 2. EDA 

In [3]:
data.replace("?",np.nan,inplace=True)

In [4]:
data.isna().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
Unnamed: 14          0
dtype: int64

In [5]:
data = data.dropna()

In [6]:
data.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
Unnamed: 14       0
dtype: int64

In [7]:
data=data.rename(columns={'Unnamed: 14': 'Annual_Income'})

In [8]:
data

age         workclass  fnlwgt   education  education-num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country Annual_Income  
0              2174             0              40  United-States         <=50K  
1                 0             0              13  United-States         <=50K  
2                 0             0              40  United-States         <=50K  
3                 0             0              40  United-States         <=50K  
4                 0             0              40           Cuba         <=50K  
...             ...           ...             ...            ...           ...  
32556             0             0              38  United-States         <=50K  
32557             0             0              40  United-States          >50K  
32558             0             0              40  United-States         <=50K  
32559             0             0              20  United-States         <=50K  
32560         15024             0              40  United-States          >50K  

[30162 rows x 15 columns]

In [9]:
data.shape

(30162, 15)

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30162 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             30162 non-null  int64 
 1   workclass       30162 non-null  object
 2   fnlwgt          30162 non-null  int64 
 3   education       30162 non-null  object
 4   education-num   30162 non-null  int64 
 5   marital-status  30162 non-null  object
 6   occupation      30162 non-null  object
 7   relationship    30162 non-null  object
 8   race            30162 non-null  object
 9   sex             30162 non-null  object
 10  capital-gain    30162 non-null  int64 
 11  capital-loss    30162 non-null  int64 
 12  hours-per-week  30162 non-null  int64 
 13  native-country  30162 non-null  object
 14  Annual_Income   30162 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [11]:
data.describe()

age        fnlwgt  education-num  capital-gain  capital-loss  \
count  30162.000000  3.016200e+04   30162.000000  30162.000000  30162.000000   
mean      38.437902  1.897938e+05      10.121312   1092.007858     88.372489   
std       13.134665  1.056530e+05       2.549995   7406.346497    404.298370   
min       17.000000  1.376900e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.176272e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.784250e+05      10.000000      0.000000      0.000000   
75%       47.000000  2.376285e+05      13.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours-per-week  
count    30162.000000  
mean        40.931238  
std         11.979984  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

### Data Manipulation

In [12]:
##a) Extract the “education” column and store it in “census_ed” .

census_ed=data['education']
census_ed

0         Bachelors
1         Bachelors
2           HS-grad
3              11th
4         Bachelors
            ...    
32556    Assoc-acdm
32557       HS-grad
32558       HS-grad
32559       HS-grad
32560       HS-grad
Name: education, Length: 30162, dtype: object

In [13]:
##b) Extract all the columns from “age” to “relationship” and store it in “census_seq”.

census_seq=data.iloc[:,:8]
census_seq

age         workclass  fnlwgt   education  education-num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

           marital-status         occupation   relationship  
0           Never-married       Adm-clerical  Not-in-family  
1      Married-civ-spouse    Exec-managerial        Husband  
2                Divorced  Handlers-cleaners  Not-in-family  
3      Married-civ-spouse  Handlers-cleaners        Husband  
4      Married-civ-spouse     Prof-specialty           Wife  
...                   ...                ...            ...  
32556  Married-civ-spouse       Tech-support           Wife  
32557  Married-civ-spouse  Machine-op-inspct        Husband  
32558             Widowed       Adm-clerical      Unmarried  
32559       Never-married       Adm-clerical      Own-child  
32560  Married-civ-spouse    Exec-managerial           Wife  

[30162 rows x 8 columns]

In [14]:
##c) Extract the column number “5”, “8”, “11” and store it in “census_col”.
census_col=data.iloc[:,[5,8,11]]
census_col

marital-status   race  capital-loss
0           Never-married  White             0
1      Married-civ-spouse  White             0
2                Divorced  White             0
3      Married-civ-spouse  Black             0
4      Married-civ-spouse  Black             0
...                   ...    ...           ...
32556  Married-civ-spouse  White             0
32557  Married-civ-spouse  White             0
32558             Widowed  White             0
32559       Never-married  White             0
32560  Married-civ-spouse  White             0

[30162 rows x 3 columns]

In [15]:
## d) Extract all the male employees who work in state-gov and store it in “male_gov”.

male_gov=data[(data['sex']=='Male') & (data['workclass']=='State-gov')]
male_gov

age  workclass  fnlwgt     education  education-num  \
0       39  State-gov   77516     Bachelors             13   
11      30  State-gov  141297     Bachelors             13   
34      22  State-gov  311512  Some-college             10   
48      41  State-gov  101603     Assoc-voc             11   
123     29  State-gov  267989     Bachelors             13   
...    ...        ...     ...           ...            ...   
32163   36  State-gov  135874     Bachelors             13   
32241   45  State-gov  231013     Bachelors             13   
32321   54  State-gov  138852       HS-grad              9   
32324   42  State-gov  138162  Some-college             10   
32360   58  State-gov  200316       HS-grad              9   

           marital-status       occupation   relationship                race  \
0           Never-married     Adm-clerical  Not-in-family               White   
11     Married-civ-spouse   Prof-specialty        Husband  Asian-Pac-Islander   
34     Married-civ-spouse    Other-service        Husband               Black   
48     Married-civ-spouse     Craft-repair        Husband               White   
123    Married-civ-spouse   Prof-specialty        Husband               White   
...                   ...              ...            ...                 ...   
32163  Married-civ-spouse            Sales        Husband               White   
32241            Divorced  Protective-serv  Not-in-family               White   
32321  Married-civ-spouse   Prof-specialty        Husband               White   
32324            Divorced     Adm-clerical      Own-child               White   
32360  Married-civ-spouse     Craft-repair        Husband               White   

        sex  capital-gain  capital-loss  hours-per-week native-country  \
0      Male          2174             0              40  United-States   
11     Male             0             0              40          India   
34     Male             0             0              15  United-States   
48     Male             0             0              40  United-States   
123    Male             0             0              50  United-States   
...     ...           ...           ...             ...            ...   
32163  Male             0             0              40  United-States   
32241  Male             0             0              40  United-States   
32321  Male             0             0              40  United-States   
32324  Male             0             0              40  United-States   
32360  Male             0             0              40  United-States   

      Annual_Income  
0             <=50K  
11             >50K  
34            <=50K  
48            <=50K  
123            >50K  
...             ...  
32163         <=50K  
32241         <=50K  
32321         <=50K  
32324         <=50K  
32360         <=50K  

[795 rows x 15 columns]

In [16]:
##e) Extract all the 39 year olds who either have a bachelor's degree or who are 
##    native of the United States and store the result in “census_us”.
 
census_us=data[(data['age']==39)& ((data['education']=='Bachelors') |(data['native-country']=='United-States'))]  
census_us

age         workclass  fnlwgt     education  education-num  \
0       39         State-gov   77516     Bachelors             13   
28      39           Private  367260       HS-grad              9   
129     39           Private  365739  Some-college             10   
166     39       Federal-gov  235485    Assoc-acdm             12   
320     39  Self-emp-not-inc  174308       HS-grad              9   
...    ...               ...     ...           ...            ...   
32146   39           Private  117381  Some-college             10   
32260   39       Federal-gov  232036  Some-college             10   
32428   39       Federal-gov  110622     Bachelors             13   
32468   39  Self-emp-not-inc  193689       HS-grad              9   
32545   39         Local-gov  111499    Assoc-acdm             12   

           marital-status        occupation   relationship  \
0           Never-married      Adm-clerical  Not-in-family   
28               Divorced   Exec-managerial  Not-in-family   
129              Divorced      Craft-repair  Not-in-family   
166         Never-married   Exec-managerial  Not-in-family   
320    Married-civ-spouse   Exec-managerial        Husband   
...                   ...               ...            ...   
32146            Divorced  Transport-moving  Not-in-family   
32260  Married-civ-spouse      Adm-clerical        Husband   
32428  Married-civ-spouse      Adm-clerical           Wife   
32468       Never-married   Exec-managerial  Not-in-family   
32545  Married-civ-spouse      Adm-clerical           Wife   

                     race     sex  capital-gain  capital-loss  hours-per-week  \
0                   White    Male          2174             0              40   
28                  White    Male             0             0              80   
129                 White    Male             0             0              40   
166                 White    Male             0             0              42   
320                 White    Male             0             0              40   
...                   ...     ...           ...           ...             ...   
32146               White    Male             0             0              65   
32260               White    Male             0             0              40   
32428  Asian-Pac-Islander  Female             0             0              40   
32468               White    Male             0             0              65   
32545               White  Female             0             0              20   

      native-country Annual_Income  
0      United-States         <=50K  
28     United-States         <=50K  
129    United-States         <=50K  
166    United-States         <=50K  
320    United-States         <=50K  
...              ...           ...  
32146  United-States         <=50K  
32260  United-States          >50K  
32428    Philippines         <=50K  
32468  United-States         <=50K  
32545  United-States          >50K  

[742 rows x 15 columns]

In [17]:
## f) Extract 200 random rows from the “census” data frame and store it in “census_200”  ## use sample keyword
census_200=data.sample(200)  
census_200

age  workclass  fnlwgt     education  education-num  \
22359   20    Private  470875       HS-grad              9   
27833   29    Private  115064       HS-grad              9   
3814    25    Private  209970     Bachelors             13   
19662   30  State-gov  190385  Some-college             10   
2258    29    Private  241431       Masters             14   
...    ...        ...     ...           ...            ...   
1464    40    Private  100584          10th              6   
22965   42    Private   97142       7th-8th              4   
9641    42    Private  121055  Some-college             10   
22192   18    Private  219841          11th              7   
19894   23  Local-gov  324637  Some-college             10   

           marital-status         occupation   relationship  \
22359  Married-civ-spouse              Sales      Own-child   
27833       Never-married      Other-service  Not-in-family   
3814        Never-married     Prof-specialty  Not-in-family   
19662       Never-married       Adm-clerical  Not-in-family   
2258   Married-civ-spouse              Sales        Husband   
...                   ...                ...            ...   
1464             Divorced       Craft-repair  Not-in-family   
22965  Married-civ-spouse   Transport-moving        Husband   
9641        Never-married              Sales  Not-in-family   
22192       Never-married  Handlers-cleaners      Own-child   
19894       Never-married       Adm-clerical  Not-in-family   

                     race     sex  capital-gain  capital-loss  hours-per-week  \
22359               Black    Male             0             0              32   
27833               White    Male             0             0              40   
3814                White  Female             0             0              40   
19662               White  Female             0             0              37   
2258                White    Male          7298             0              40   
...                   ...     ...           ...           ...             ...   
1464   Amer-Indian-Eskimo    Male             0             0              40   
22965               White    Male             0             0              40   
9641                White    Male             0             0              45   
22192               White    Male             0             0              12   
19894               White    Male             0             0              30   

      native-country Annual_Income  
22359  United-States         <=50K  
27833  United-States         <=50K  
3814   United-States         <=50K  
19662  United-States         <=50K  
2258   United-States          >50K  
...              ...           ...  
1464   United-States         <=50K  
22965  United-States         <=50K  
9641   United-States         <=50K  
22192  United-States         <=50K  
19894  United-States         <=50K  

[200 rows x 15 columns]

In [18]:
## g) Get the count of different levels of the “workclass” column.
data['workclass'].value_counts()

Private             22286
Self-emp-not-inc     2499
Local-gov            2067
State-gov            1279
Self-emp-inc         1074
Federal-gov           943
Without-pay            14
Name: workclass, dtype: int64

In [19]:
## h) Calculate the mean of the “capital.gain” column grouped according to “workclass”.
data.groupby('workclass')['capital-gain'].mean()

workclass
Federal-gov          832.321315
Local-gov            829.230285
Private              879.858207
Self-emp-inc        4810.746741
Self-emp-not-inc    1913.134454
State-gov            684.306489
Without-pay          487.857143
Name: capital-gain, dtype: float64

In [20]:
## k) Calculate the percentage of married people in the census data.

cal = data[(data['marital-status']=='Married-civ-spouse') | (data['marital-status']== 'Married-AF-spouse')]

(len(cal)/len(data))*100

### per%=(married/total)

46.7011471387839

In [21]:
data['marital-status'].value_counts()   # married = 14065+21+370

Married-civ-spouse       14065
Never-married             9726
Divorced                  4214
Separated                  939
Widowed                    827
Married-spouse-absent      370
Married-AF-spouse           21
Name: marital-status, dtype: int64

In [22]:
marr= 14065+21+370
total=len(data['marital-status'])
p=(marr/total)
p*100

47.92785624295471

## Label Encoding 

In [23]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
##Independent Col's
data['workclass'] = labelencoder.fit_transform(data['workclass'])
data['education'] = labelencoder.fit_transform(data['education'])
data['marital-status'] = labelencoder.fit_transform(data['marital-status'])
data['occupation'] = labelencoder.fit_transform(data['occupation'])
data['relationship'] = labelencoder.fit_transform(data['relationship'])
data['race'] = labelencoder.fit_transform(data['race'])
data['sex'] = labelencoder.fit_transform(data['sex'])
data['native-country'] = labelencoder.fit_transform(data['native-country'])


In [24]:
x=data.iloc[:,:-1]

In [25]:
x

age  workclass  fnlwgt  education  education-num  marital-status  \
0       39          5   77516          9             13               4   
1       50          4   83311          9             13               2   
2       38          2  215646         11              9               0   
3       53          2  234721          1              7               2   
4       28          2  338409          9             13               2   
...    ...        ...     ...        ...            ...             ...   
32556   27          2  257302          7             12               2   
32557   40          2  154374         11              9               2   
32558   58          2  151910         11              9               6   
32559   22          2  201490         11              9               4   
32560   52          3  287927         11              9               2   

       occupation  relationship  race  sex  capital-gain  capital-loss  \
0               0             1     4    1          2174             0   
1               3             0     4    1             0             0   
2               5             1     4    1             0             0   
3               5             0     2    1             0             0   
4               9             5     2    0             0             0   
...           ...           ...   ...  ...           ...           ...   
32556          12             5     4    0             0             0   
32557           6             0     4    1             0             0   
32558           0             4     4    0             0             0   
32559           0             3     4    1             0             0   
32560           3             5     4    0         15024             0   

       hours-per-week  native-country  
0                  40              38  
1                  13              38  
2                  40              38  
3                  40              38  
4                  40               4  
...               ...             ...  
32556              38              38  
32557              40              38  
32558              40              38  
32559              20              38  
32560              40              38  

[30162 rows x 14 columns]

In [26]:
##Dep
data['AnnualIncome'] = labelencoder.fit_transform(data['Annual_Income'])

In [27]:
y=data.iloc[:,-1]

In [28]:
y

0        0
1        0
2        0
3        0
4        0
        ..
32556    0
32557    1
32558    0
32559    0
32560    1
Name: AnnualIncome, Length: 30162, dtype: int32

# Machine Learning Modeling

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import *

## Linear Regression

In [31]:
# ● Build a linear model on the test set where the dependent variable is“hours.per.week” and the independent variable is “education.num”.
# independent --> education num
# dependent ---->hours per week

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
x1= data[['education-num']]
y1= data['hours-per-week']
from sklearn.linear_model import *
from sklearn.model_selection import train_test_split

In [34]:
x1_train,x1_test,y1_train,y1_test=train_test_split(x1,y1,test_size=.30,random_state=42)
lr= LinearRegression()
lr.fit(x1_train,y1_train)
y1_pred=lr.predict(x1_test)

In [35]:
y1_pred

array([44.30810976, 40.20968024, 40.20968024, ..., 42.94196659,
       40.20968024, 42.94196659])

In [36]:
##ACCURACY
accuracy1 = r2_score(y1_test,y1_pred)
accuracy1

0.02808393704627965

In [37]:
## RSME//ERROR RATE
mean_squared_error(y1_test,y1_pred)

137.81263845871413

## Simple Logistic Regression 

In [38]:
# Independent--- occupation 
# Dep Annual--- Income 

In [39]:
X=data['occupation']
X=pd.DataFrame(X)
X

occupation
0               0
1               3
2               5
3               5
4               9
...           ...
32556          12
32557           6
32558           0
32559           0
32560           3

[30162 rows x 1 columns]

In [40]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()

In [41]:
Y=data["Annual_Income"]
Y=l.fit_transform(Y)
Y

array([0, 0, 0, ..., 0, 0, 1])

In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=.35,random_state=1)

In [43]:
log=LogisticRegression()

In [44]:
log.fit(X_train,Y_train)

LogisticRegression()

In [45]:
Y_pred=log.predict(X_test)

In [46]:
Y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [47]:
accuracy_score(Y_pred,Y_test)

0.7513498152884343

In [48]:
confusion_matrix(Y_test,Y_pred)

array([[7932,    0],
       [2625,    0]], dtype=int64)

## Multiple Logistic Regression

In [ ]:
# Independent--- age,workclass,education  
# Dep Annual--- Income 

In [49]:
data.head(2)

age  workclass  fnlwgt  education  education-num  marital-status  \
0   39          5   77516          9             13               4   
1   50          4   83311          9             13               2   

   occupation  relationship  race  sex  capital-gain  capital-loss  \
0           0             1     4    1          2174             0   
1           3             0     4    1             0             0   

   hours-per-week  native-country Annual_Income  AnnualIncome  
0              40              38         <=50K             0  
1              13              38         <=50K             0

In [55]:
X2 =  pd.DataFrame(data,columns=["age","workclass","education"])
X2

age  workclass  education
0       39          5          9
1       50          4          9
2       38          2         11
3       53          2          1
4       28          2          9
...    ...        ...        ...
32556   27          2          7
32557   40          2         11
32558   58          2         11
32559   22          2         11
32560   52          3         11

[30162 rows x 3 columns]

In [59]:
Y2=data.iloc[:,-1]
Y2

0        0
1        0
2        0
3        0
4        0
        ..
32556    0
32557    1
32558    0
32559    0
32560    1
Name: AnnualIncome, Length: 30162, dtype: int32

In [60]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
X2_train,X2_test,Y2_train,Y2_test=train_test_split(X2,Y2,test_size=.20,random_state=1)

In [61]:
mlog=LogisticRegression()

In [62]:
mlog.fit(X2_train,Y2_train)

LogisticRegression()

In [64]:
Y2_pred=mlog.predict(X2_test)

In [65]:
Y2_pred

array([0, 0, 0, ..., 0, 0, 0])

In [104]:
accuracy_score(Y2_pred,Y2_test)

0.7293220619923753

In [105]:
confusion_matrix(Y2_test,Y2_pred)

array([[4350,  133],
       [1500,   50]], dtype=int64)

## Decision Tree 

In [122]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [130]:
dtc=DecisionTreeClassifier()
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.30, random_state=42)

In [131]:
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [132]:
p2=dtc.predict(x_test)

In [133]:
p2

array([0, 1, 0, ..., 1, 0, 0])

In [134]:
confusion_matrix(y_test,p2)

array([[5894,  873],
       [ 880, 1402]], dtype=int64)

In [135]:
DTC= accuracy_score(y_test,p2)
DTC

0.806276936678086

## Random Forest

In [136]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [137]:
rfc=RandomForestClassifier(n_estimators=300)
x_train, x_test, y_train, y_test=train_test_split(x,y, train_size=0.80, random_state=42)

In [138]:
rfc.fit(x_train, y_train)

RandomForestClassifier(n_estimators=300)

In [139]:
p1=rfc.predict(x_test)

In [140]:
p1

array([0, 0, 0, ..., 1, 1, 0])

In [141]:
confusion_matrix(y_test,p1)

array([[4168,  335],
       [ 545,  985]], dtype=int64)

In [142]:
RFC= accuracy_score(y_test,p1)

In [143]:
RFC

0.854135587601525

## Overall Accuracy of the ML Models


In [144]:
print('Accuracy of Linear Regression Model: ')
print(accuracy1)
print('Accuracy of Simple Logistic Regression Model: ')
print(accuracy_score(Y_pred,Y_test))
print('Accuracy of Multiple Logistic Regression Model: ')
print(accuracy_score(Y2_pred,Y2_test)) 
print('Accuracy of Decision Tree Model: ')
print(DTC)
print('Accuracy of Random Forest Model: ')
print(RFC)

Accuracy of Linear Regression Model: 
0.02808393704627965
Accuracy of Simple Logistic Regression Model: 
0.7513498152884343
Accuracy of Multiple Logistic Regression Model: 
0.7293220619923753
Accuracy of Decision Tree Model: 
0.806276936678086
Accuracy of Random Forest Model: 
0.854135587601525
